# Generated by Django 2.2.10 on 2020-03-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(default='default_product', max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_votes',
            field=models.IntegerField(default=1),
        ),
    ]
